#!/bin/bash

USER_ID=$(id -u)
USERNAME=$(id -un) 
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
IMAGE=rishabh880/ros-docker-robomuse

echo "Starting the container"
sudo docker run -it --rm \
		--net=host \
	 	--pid=host \
		--privileged \
		-e USER_ID=${USER_ID} \
		-e USERNAME=${USERNAME} \
		-v ${XSOCK}:${XSOCK}:rw \
		-v ${XAUTH}:${XAUTH}:rw \
		-e XAUTHORITY=${XAUTH} \
		-e DISPLAY=$DISPLAY \
		-v /home/${USERNAME}:/mnt/host \
		--cap-add=ALL \
		--name ros-docker-${USERNAME} \
		--expose=9090 \
		rishabh880/ros-docker-robomuse
